[limits]
safe_max_loc = 50
max_files = 4
allow_db_migrations = false
allow_secret_changes = false

[canary]
enabled = true
traffic_percent = 10
observe_seconds = 600
rollback_error_rate_pct = 1.0
rollback_p95_ms = 1200

[credits]
included = 10
rollover_months = 1
overage_price_usd = 29

[tests]
require_smoke = true
require_schema_check = true
