name = "educonnect-hq-lite"
main = "src/index.js"
account_id = "51eb164d0cf82ef62825aacbb5e1150a"
compatibility_date = "2025-11-02"

kv_namespaces = [
  { binding = "STATUS", id = "2885b21636b34375b6d12ae42f703993" },
  { binding = "AUDIT",  id = "2a458f87826b44088f1071e57f3524d2"  }
]

[triggers]
crons = ["*/5 * * * *"]

[vars]
DEPLOY_ID = "20251102_201526Z"
WRANGLER_VERSION = "4.33.1"

